apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sjob
  namespace: wahed
  labels:
    app: k8sjob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sjob
  template:
    metadata:
      labels:
        app: k8sjob
    spec:
      containers:
        - name: k8sjob
          image: ghcr.io/wahed-tech/k8sjob:latest
          ports:
            - containerPort: 8080
          env:
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: k8sjob-github
                  key: client-id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: k8sjob-github
                  key: client-secret
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
