name: Deploy
on:
  push:
    branches:
      - master
      - feature/deploy
    tags:
      - '*'
env:
  TERM: DUMB
  DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
  IMAGE: wahedtech/k8sjob
jobs:
  docker_image:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4
      - name: Set BUILD_FROM, TAG variables
        run: |
          echo "BUILD_FROM=$(if [[ ${{ startsWith(github.ref, 'refs/tags/') }} == true ]]; then echo 'tag'; else echo 'branch'; fi )" >> $GITHUB_ENV
          echo "TAG=$(if [[ ${{ startsWith(github.ref, 'refs/tags/') }} == true ]]; then echo ${{ github.ref_name }}; else echo ${{ github.sha }}; fi )" >> $GITHUB_ENV
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: go.sum
          go-version-file: 'go.mod'
      - name: Set go flags
        run: |
          go env -w GOSUMDB=off
          go env -w GOPRIVATE=github.com/wahed-tech/
      - name: Setup Token
        run: git config --global url."https://${DEPLOY_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build app
        run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -trimpath -o build/app-amd64 .
          GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -trimpath -o build/app-arm64 .
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "wahedtech"
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker meta
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=ref,event=tag
            type=sha,format=long,prefix=
            type=raw,value=latest
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            TARGETARCH
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
      - name: Trigger Spinnaker deploy
        run: |
          curl -X POST https://gate.spin.prod.wahed.tech/webhooks/webhook/dockercloud \
            -H "Content-Type: application/json" \
            -d '{
                  "secret":"'${{ secrets.SPIN_SECRET }}'",
                  "built-from": "'${{ env.BUILD_FROM }}'",
                  "branch": "'${{ github.ref_name }}'",
                  "tag": "'${{ github.ref_name }}'",
                  "artifacts": [
                    {
                      "type": "docker/image",
                      "reference": "'${IMAGE}':'${TAG}'",
                      "name": "'${IMAGE}'",
                      "version": "'${TAG}'"
                    }
                  ]
                }'
